// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Level int32

const (
	Level_WARNING Level = 0
	Level_FATAL   Level = 1
	Level_SEVERE  Level = 2
)

var Level_name = map[int32]string{
	0: "WARNING",
	1: "FATAL",
	2: "SEVERE",
}

var Level_value = map[string]int32{
	"WARNING": 0,
	"FATAL":   1,
	"SEVERE":  2,
}

func (x Level) String() string {
	return proto.EnumName(Level_name, int32(x))
}

func (Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

type Http struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Level                Level    `protobuf:"varint,2,opt,name=level,proto3,enum=protobuf.Level" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Http) Reset()         { *m = Http{} }
func (m *Http) String() string { return proto.CompactTextString(m) }
func (*Http) ProtoMessage()    {}
func (*Http) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Http) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Http.Unmarshal(m, b)
}
func (m *Http) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Http.Marshal(b, m, deterministic)
}
func (m *Http) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Http.Merge(m, src)
}
func (m *Http) XXX_Size() int {
	return xxx_messageInfo_Http.Size(m)
}
func (m *Http) XXX_DiscardUnknown() {
	xxx_messageInfo_Http.DiscardUnknown(m)
}

var xxx_messageInfo_Http proto.InternalMessageInfo

func (m *Http) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Http) GetLevel() Level {
	if m != nil {
		return m.Level
	}
	return Level_WARNING
}

func init() {
	proto.RegisterEnum("protobuf.Level", Level_name, Level_value)
	proto.RegisterType((*Http)(nil), "protobuf.Http")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0xee, 0x5c,
	0x2c, 0x1e, 0x25, 0x25, 0x05, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x90, 0x2a, 0x17, 0x6b, 0x4e, 0x6a, 0x59,
	0x6a, 0x8e, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x9f, 0x11, 0xbf, 0x1e, 0x4c, 0xaf, 0x9e, 0x0f, 0x48,
	0x38, 0x08, 0x22, 0xab, 0xa5, 0xcd, 0xc5, 0x0a, 0xe6, 0x0b, 0x71, 0x73, 0xb1, 0x87, 0x3b, 0x06,
	0xf9, 0x79, 0xfa, 0xb9, 0x0b, 0x30, 0x08, 0x71, 0x72, 0xb1, 0xba, 0x39, 0x86, 0x38, 0xfa, 0x08,
	0x30, 0x0a, 0x71, 0x71, 0xb1, 0x05, 0xbb, 0x86, 0xb9, 0x06, 0xb9, 0x0a, 0x30, 0x25, 0xb1, 0x81,
	0xcd, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x37, 0x92, 0x68, 0x94, 0x00, 0x00, 0x00,
}
