// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sharedlinks.proto

package schema

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SharedLink is a struct that defines the detail info shared by users.
type SharedLink struct {
	Url                  string            `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Params               map[string]string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Hash                 string            `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SharedLink) Reset()         { *m = SharedLink{} }
func (m *SharedLink) String() string { return proto.CompactTextString(m) }
func (*SharedLink) ProtoMessage()    {}
func (*SharedLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_8be0ae7d25e22020, []int{0}
}

func (m *SharedLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedLink.Unmarshal(m, b)
}
func (m *SharedLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedLink.Marshal(b, m, deterministic)
}
func (m *SharedLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedLink.Merge(m, src)
}
func (m *SharedLink) XXX_Size() int {
	return xxx_messageInfo_SharedLink.Size(m)
}
func (m *SharedLink) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedLink.DiscardUnknown(m)
}

var xxx_messageInfo_SharedLink proto.InternalMessageInfo

func (m *SharedLink) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SharedLink) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *SharedLink) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

// SharedLinkStorage uses a ordered list of params to get the same hash.
type SharedLinkStorage struct {
	Url                  string            `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Param                []*ShareLinkParam `protobuf:"bytes,2,rep,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SharedLinkStorage) Reset()         { *m = SharedLinkStorage{} }
func (m *SharedLinkStorage) String() string { return proto.CompactTextString(m) }
func (*SharedLinkStorage) ProtoMessage()    {}
func (*SharedLinkStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8be0ae7d25e22020, []int{1}
}

func (m *SharedLinkStorage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedLinkStorage.Unmarshal(m, b)
}
func (m *SharedLinkStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedLinkStorage.Marshal(b, m, deterministic)
}
func (m *SharedLinkStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedLinkStorage.Merge(m, src)
}
func (m *SharedLinkStorage) XXX_Size() int {
	return xxx_messageInfo_SharedLinkStorage.Size(m)
}
func (m *SharedLinkStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedLinkStorage.DiscardUnknown(m)
}

var xxx_messageInfo_SharedLinkStorage proto.InternalMessageInfo

func (m *SharedLinkStorage) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SharedLinkStorage) GetParam() []*ShareLinkParam {
	if m != nil {
		return m.Param
	}
	return nil
}

type ShareLinkParam struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareLinkParam) Reset()         { *m = ShareLinkParam{} }
func (m *ShareLinkParam) String() string { return proto.CompactTextString(m) }
func (*ShareLinkParam) ProtoMessage()    {}
func (*ShareLinkParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_8be0ae7d25e22020, []int{2}
}

func (m *ShareLinkParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareLinkParam.Unmarshal(m, b)
}
func (m *ShareLinkParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareLinkParam.Marshal(b, m, deterministic)
}
func (m *ShareLinkParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareLinkParam.Merge(m, src)
}
func (m *ShareLinkParam) XXX_Size() int {
	return xxx_messageInfo_ShareLinkParam.Size(m)
}
func (m *ShareLinkParam) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareLinkParam.DiscardUnknown(m)
}

var xxx_messageInfo_ShareLinkParam proto.InternalMessageInfo

func (m *ShareLinkParam) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ShareLinkParam) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*SharedLink)(nil), "schema.SharedLink")
	proto.RegisterMapType((map[string]string)(nil), "schema.SharedLink.ParamsEntry")
	proto.RegisterType((*SharedLinkStorage)(nil), "schema.SharedLinkStorage")
	proto.RegisterType((*ShareLinkParam)(nil), "schema.ShareLinkParam")
}

func init() { proto.RegisterFile("sharedlinks.proto", fileDescriptor_8be0ae7d25e22020) }

var fileDescriptor_8be0ae7d25e22020 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xce, 0x48, 0x2c,
	0x4a, 0x4d, 0xc9, 0xc9, 0xcc, 0xcb, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b,
	0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x54, 0x5a, 0xca, 0xc8, 0xc5, 0x15, 0x0c, 0x96, 0xf5, 0xc9, 0xcc,
	0xcb, 0x16, 0x12, 0xe0, 0x62, 0x2e, 0x2d, 0xca, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02,
	0x31, 0x85, 0xcc, 0xb8, 0xd8, 0x0a, 0x12, 0x8b, 0x12, 0x73, 0x8b, 0x25, 0x98, 0x14, 0x98, 0x35,
	0xb8, 0x8d, 0xe4, 0xf4, 0x20, 0x3a, 0xf5, 0x10, 0xba, 0xf4, 0x02, 0xc0, 0x0a, 0x5c, 0xf3, 0x4a,
	0x8a, 0x2a, 0x83, 0xa0, 0xaa, 0x85, 0x84, 0xb8, 0x58, 0x32, 0x12, 0x8b, 0x33, 0x24, 0x98, 0xc1,
	0x46, 0x81, 0xd9, 0x52, 0x96, 0x5c, 0xdc, 0x48, 0x4a, 0x41, 0x96, 0x65, 0xa7, 0x56, 0xc2, 0x2c,
	0xcb, 0x4e, 0xad, 0x14, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x02, 0x8b,
	0x41, 0x38, 0x56, 0x4c, 0x16, 0x8c, 0x4a, 0xc1, 0x5c, 0x82, 0x08, 0x0b, 0x83, 0x4b, 0xf2, 0x8b,
	0x12, 0xd3, 0x53, 0xb1, 0xb8, 0x56, 0x87, 0x8b, 0x15, 0x6c, 0x3f, 0xd4, 0xb1, 0x62, 0x28, 0x8e,
	0x05, 0x69, 0x05, 0xdb, 0x1f, 0x04, 0x51, 0xa4, 0x64, 0xc1, 0xc5, 0x87, 0x2a, 0x41, 0xac, 0x93,
	0x92, 0xd8, 0xc0, 0xa1, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x05, 0xe8, 0xbb, 0x5a,
	0x01, 0x00, 0x00,
}
